language: python
python:
  - 2.7
sudo: false
cache:
  directories:
  - test.plone_addon/eggs

env:
  matrix:
    - PLONE_VERSION=4.0.10
    - PLONE_VERSION=4.1.6
    - PLONE_VERSION=4.2.7
    - PLONE_VERSION=4.3.4
    - PLONE_VERSION=5.0a3

matrix:
  allow_failures:
    - env: PLONE_VERSION=4.0.10
    - env: PLONE_VERSION=4.1.6
    - env: PLONE_VERSION=4.2.7

install:
  - sed -ie "s/^plone.version.*/plone.version = $PLONE_VERSION/g" test_answers.ini
  - python bootstrap-buildout.py --setuptools-version=8.3
  - bin/pip install distutils
  - bin/buildout

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bin/code-analysis
  - bin/nosetests
  - bin/test

notifications:
  email:
    - travis-reports@plone.com
